server:
  port: 9089

spring:
  profiles:
    include: secret

# 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///pokemon?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: username
    password: password
  data:
    mongodb:
      uri: mongodb://username:password@localhost:27017/pokemon

# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
